### ISSUE TITLE
onion routing

### ISSUE THREAD

**Issue by zack-bitcoin** [BumblebeeBat/FlyingFox#26]
encrypted messaging would be even better if it onioned the routing. that is where you have layers of encryption, and the message passes through multiple nodes and gets another layer removed each time. We should do this to hide the location of the validators.

**Comment by eragmus** [comment]
This has been suggested on the Lightning dev mailing list and debated quite a bit. I think there is also some code. Perhaps review those mailing list posts and help out Rusty, et. al with optimization of the idea/code.
