### ISSUE TITLE
Crash on start in Ubuntu Server 14.04 LTS

### ISSUE THREAD

**Issue by ChrisCalderon** [BumblebeeBat/FlyingFox#30]
This is the terminal output 

```
larry@larrybox:~/FlyingFox$ sh start.sh
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> FlyingFox (compile)
GO TO THIS WEBSITE -------> http://localhost:3011/main.html
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]

Eshell V7.1  (abort with ^G)
1> {"init terminating in do_boot",{undef,[{port,start_server,[],[]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,669}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()
```

**Comment by zack-bitcoin** [comment]
I added a feature so you can change the port when you turn the server on.
for example, to start on port 3020:
sh start.sh 3020

solution:
the node will always start with the sever turned off. 
Then you use commands to start the server on whichever port you want:
server:start(3020).

**Comment by zack-bitcoin** [comment]
The problem is that I moved the flying_fox.app file without moving a pointer to it. The compiler didn't know what it had to compile.

It should work now.
