### ISSUE TITLE
what is this project about?

### ISSUE THREAD

**Issue by csbzy** [BumblebeeBat/FlyingFox#31]

**Comment by csbzy** [comment]
all xhr request is return `i can't handle this`
eg.
`["get_msg",[52,36,106,100],3010]`

**Comment by zack-bitcoin** [comment]
This project is competing against Ethereum. It is a system for smart contracts.

Flying Fox has a built-in encrypted chat system. It uses the same address as you use to spend your coins. So you can be sure that you are talking to the person who owns the coins.

The "get_message" command is in /src/networking/internal_handler.erl
It is used to check if you have any messages in your inbox.

It is designed to use a browser for sending and receiving messages.
http://localhost:3011/main.html

Thank you for testing.
