### ISSUE TITLE
tcp -> HTTP and UDP>

### ISSUE THREAD

**Issue by zack-bitcoin** [BumblebeeBat/FlyingFox#8]
The idea is to have a standard interface in order to be able to talk to different clients and frontends that are going to use our node. That being said, we would want to be able to talk also to browsers. This means we need to have some sort of HTTP interface in order to serve both JSON (AJAX) and/or WebSockets if we want to stream real-time data from our nodes to the different frontends.

**Comment by zack-bitcoin** [comment]
we want to talk with javascript, so we should have http.
TCP is too slow for talking with other nodes, we should upgrade to UDP.

**Comment by arpunk** [comment]
@zack-bitcoin The TCP speed issue is going to be tracked in another issue.

**Comment by zack-bitcoin** [comment]
I got ranch set up. It works well, so ill just use this for now.
