### ISSUE TITLE
Build up a glossary of all the terms we are using

### ISSUE THREAD

**Issue by arpunk** [BumblebeeBat/FlyingFox#9]
In order to have a solid and single understanding we need to come up with a glossary of terms used in the FlyingFox protocol. This will make us all read the same page when we talk and discuss about the protocol and how to further extend it.

**Comment by zack-bitcoin** [comment]
what words need definitions?
channel, oracle, cash, bonds, wait-money, block, transaction, consensus state, channel state, decision, validator, contract for difference

anything else?

**Comment by zack-bitcoin** [comment]
I started a small glossary. We can grow it as we realize more words.

**Comment by arpunk** [comment]
@zack-bitcoin We can write it in the wiki: https://github.com/BumblebeeBat/FlyingFox/wiki
